version: "3.8"

services:
  bracelet-simulator:
    build: ./bracelet-simulator
    depends_on:
      - boitier-server

  boitier-server:
    build: ./boitier-server
    ports:
      - "5000:5000"
    depends_on:
      - cloud-backend
      - kafka
    environment:
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1431783528843972619/TL_S08qiZAGryAwiFwLCK4FOJI0DflAVz4l5v4VeVX3EJNCIF_wv_rW1wLg1MzQeXwEo
      
  web-backend:
    build: ./web-interface-backend
    ports:
      - "3030:3030"
    depends_on:
      - influxdb

  cloud-backend:
    build: ./cloud-backend
    ports:
      - "3005:3005"
    depends_on:
      - kafka
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=1tUJ8TUG91tkaMeFjIUVrgAfdXT1KrOXgJmI0cUncn9y3_NrHQhkaHRbSWlcblHLWHe5EBwmXpW77E-ZVitLXA==
      - INFLUX_ORG=archimed
      - INFLUX_BUCKET=health

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: abcdefghijklmnopqrstuv
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-broker-api-versions --bootstrap-server kafka:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  front-visualiser:
    build: ./front-visualiser
    ports:
      - "5173:80"
    depends_on:
      - cloud-backend


  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_BUCKET=health
      - DOCKER_INFLUXDB_INIT_ORG=archimed
      - DOCKER_INFLUXDB_INIT_RETENTION=7d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE=/run/secrets/influx-token
    secrets:
      - influx-token


secrets:
  influx-token:
    file: ./influx-token.txt